### ISSUE TITLE
Jackson BOM should not have managed dependency for third-party libraries (woodstox, stax-api)

### ISSUE THREAD

**Issue by snicoll** [FasterXML/jackson-bom#99]
The BOM has recently add dependency management [for third-party libraries](https://github.com/FasterXML/jackson-bom/commit/8ab1c24a786753e6f2e0dd61f708777c5ef5da67). This makes the inclusion of the BOM in other projects more complicated than it should.

While some Jackson component may have a need for a particular dependency and baseline, it is already expressed in the published pom of the component. Please consider reverting as it is flagged as an non-compliant BOM in Spring Boot. Others may be impacted if they manage `org.codehaus.woodstox` and want to manage that on their own.

**Comment by cowtowncoder** [comment]
Hmhm. This was via #90 due to user request #88. So conflicting wishes

But I wonder if this could be fixed by changing so that `jackson-bom` only provides preferred versions as properties, and then actual modules (jackson-dataformat-xml, jackson-jaxrs-xml-provider) defined managed dependency.

Would this work?

**Comment by snicoll** [comment]
> Hmhm. This was via https://github.com/FasterXML/jackson-bom/pull/90 due to user request https://github.com/FasterXML/jackson-bom/issues/88. So conflicting wishes

Thanks for sharing the context. IMO, #88 is requesting to manage  `com.fasterxml.woodstox` and that looks fair enough considering it is a module strongly tied to Jackson. That doesn't mean the Jackson bom should manage woodstox itself. I think that's the main issue.

> But I wonder if this could be fixed by changing so that jackson-bom only provides preferred versions as properties,

I don't know what you'd fix except expressing a preference for a woodstox version in a property. The BOM is imported in Maven so its properties aren't imported in the project. I can't see what it would bring. If you want to make sure that those modules use the same third-party deps a common parent is the way to go.

I think a good compromise would be to drop the dependency management for `org.codehaus.woodstox`.

**Comment by cowtowncoder** [comment]
Oh,  by `org.codehaus.woodstox` you mean `stax2-api`, which is depended by Woodstox (Woodstox implements that API).

What I meant was simply that the `<managedDependency>` for Woodstox and stax2-api (both are really needed to keep things consistent, I think) would be moved out `jackson-bom`, and into components that actually require them -- XML module and XML JAX-RS/Jakarta-RS providers.

Hmmh. But, I guess I do not see how this would work wrt #88 -- the whole idea was to resolve inconsistent version of Woodstox.

Note that consistent version of `stax2-api` is about as important as Woodstox (which implements) it, I think.

But... if you build `jackson-bom` locally, with `stax2-api` managed version removed, does that actually solve the problem?

I am not quite sure how to proceed here to be honest. As I am trying to solve problems that seem conflicting, and neither problem I actually have ever faced :)

**Comment by rob-valor** [comment]
Hi, I didn't look at the changes being made for my #88 request. Indeed the request was too only add the Jackson woodstox dependency management to the bom. That simplifies the version management of Jackson dependencies.

Adding third party dependencies to the Jackson bom can accidentally cause issues in projects using the bom. Since the order of the managed dependencies will decide which version is used eventually, it could break dependency management in those projects. Also, when one would depend on another dependency which transitively pulls in the same third party dependency,  one is not informed when version conflicts would occur because of such _transitive_ dependency management.

I can't remember reading the last sentence in the comment regarding `aalto-xml`, I must have skipped that one. That should have been a trigger to check the changes being made. Sorry about that.

I created that issue because we use Spring Boot and there the Jackson bom is used and we still needed to manage a Jackson dependency explicitly.

**Comment by snicoll** [comment]
> But... if you build jackson-bom locally, with stax2-api managed version removed, does that actually solve the problem?

I don't need to build it locally. It's a conceptual thing, BOM should not provide dependency management for external deps: their role is to make sure dependencies _of the project_ are consistent with a single version. You import the bom of that version and whatever modules the project defines has the correct version.

**Comment by snicoll** [comment]
I should add that my original request was about those two libraries because you flagged them as "third party" but `com.fasterxml.woodstox:woodstox-core` isn't really third-party, is it? Doesn't it relate to Jackson one way or the other? (given the groupId). 

If it doesn't relate to Jackson directly, then my vote would be to revert that as well for the conceptual reason I've raised in my previous comment. I can see how it would make sense for pragmatic reason though.

**Comment by cowtowncoder** [comment]
> I don't need to build it locally. It's a conceptual thing, BOM should not provide dependency management for external deps: their role is to make sure dependencies of the project are consistent with a single version. You import the bom of that version and whatever modules the project defines has the correct version.

What I meant is the failure, symptom -- to reproduce the issue you have. I understand conceptual concerns but am more interested in actual (not theoretical) problem you have. Hence I am interested in knowing if both managed dependencies having conflict with spring bom.

**Comment by cowtowncoder** [comment]
> I should add that my original request was about those two libraries because you flagged them as "third party" but com.fasterxml.woodstox:woodstox-core isn't really third-party, is it? Doesn't it relate to Jackson one way or the other? (given the groupId).

From perspective of Jackson, both are 3rd party, they are by same conceptual organization. But not part of set of Jackson components.

Similarly `stax2-api` is not part of Woodstox, regardless of group id. It is maintained and published by Woodstox project but separate, as it's depended on by not just Woodstox but Aalto and (possibly / potentially) by other Stax implementations.

**Comment by snicoll** [comment]
> What I meant is the failure, symptom -- to reproduce the issue you have

The failure symptom is conceptual. Anybody that wants to manage `stax2-api` may be in trouble because an unrelated BOM started to have an opinion about it. In Spring Boot, our option is to start managing that dependency (although we shouldn't really have to) to make sure versions are consistent. For now we allowed those two deps to be managed by Jackson but we'd like this to be changed for the arguments exposed above.

> Similarly stax2-api is not part of Woodstox, regardless of group id. It is maintained and published by Woodstox project but separate,

Then I'd argue that Jackson shouldn't have dependency management for it.

**Comment by cowtowncoder** [comment]
Ok so put another way, there is conceptual concern but no actual failure. yet.

**Comment by cowtowncoder** [comment]
And just to clarify: I don't mean that this would not be a real problem, but that unlike the original issue for which change was made, there is no concrete failure to tackle. Instead it is just the concern of multiple BOMs ending upping with overlapping versions leading to version conflicts, perhaps not unlike the original issue itself.

I think I am inclined to do what is requested here and just define desired versions as properties and make modules that do have direct dependency use that.  It is still slightly better from Jackson component perspective as there are 3 repos requiring these versions to be updated.

**Comment by cowtowncoder** [comment]
Done. Downstream Jackson components now no longer depend on managed dependencies but do use version properties jackson-bom defines (to centralize dependent versions).
Change will be in 2.19.1, 2.20 and 3.0.0-rc5.

**Comment by rob-valor** [comment]
Hi @cowtowncoder , regarding all the changes being made lately because of my (unfortunate) request, I still have a question: how do **you** see the boms' scope? Is it a  `com.fasterxml` or `com.fasterxml.jackson`  _umbrella_? That's, I think, also what @snicoll was wondering. 

I'm asking because we use Spring Boot. Spring Boot manages both their own, as well as (second: springframework and) third party dependencies. Among such third party dependencies are Jacksons' through the Jackson bom. The reason Spring Boot manages all those third party dependencies is because it is an entire _application development framework_. That way, users of such framework can profit of the opinionated _ecosystem_ managed by others.

A library like yours is unlikely to manage third party dependencies through a bom for reasons alread being clear. For me it's just not clear whether the fasterxml woodstox can be seen as a jackson-woodstox module or really a separate standalone woodstox module (usable anywhere else), and not directly related to jackson. I really don't know the fasterxml umbrella well enough to come up with a conclusion myself 😉.

I'll pick up this conversation again within a few hours. It's 2:00am so more important things to do now 🥱

**Comment by cowtowncoder** [comment]
Good question! TL;DNR: Woodstox is not under Jackson umbrella: it is an older established library.
Similar to how `java-uuid-generator` (https://mvnrepository.com/artifact/com.fasterxml.uuid/java-uuid-generator) is not.
Both of which actually predate Jackson project (uuid generator being my first actively developed and still maintained library, Woodstox second).
`com.fasterxml` namespace is just a convenient umbrella for namespaces, all under Github FasterXML organization.

So in that sense Woodstox version does not belong in `jackson-bom`. Especially considering that versioning is not synchronized.

But I guess there is also the implied suggestion for "should there not be `com.fasterxml:fasterxml-bom` or something. Being only very loosely coupled, I probably would not want to create one, not the least because versioning of bom itself would become challenging (Woodstox and Jackson following different schedules).

I hope this makes more sense now.

**Comment by snicoll** [comment]
>  I don't mean that this would not be a real problem, but that unlike the original issue for which change was made, there is no concrete failure to tackle

Because I didn't take the time to provide a sample as I thought we could agree on a theoretical level. You only need a project that imports the jackson-bom and has a dependency that uses `stax2-api` as a transitive dependency. If you upgrade to `2.19.0` then your version of `stax2-api` changes, potentially to an incompatible version of what you had before. Even if you don't use any of the woodstox stuff that Jackson provides integration for. To me that last part is the most compelling argument: if this isn't a mandatory dependency it makes even less sense to manage its version.

Anyways, thanks for reverting
